{% set name = "bbknn" %} 
{% set version = "1.3.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3b2b7eed70a362092b9fa080ff89d936b94d321045e86008763184ea1109f9b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - python-annoy
    - numpy >=1.13
    - pip
    - python
    - scipy
    - scikit-learn
    - umap-learn
  run:
    - python-annoy
    - numpy >=1.13
    - python
    - scipy
    - scikit-learn
    - umap-learn

test:
  imports:
    - bbknn

about:
  home: https://github.com/Teichlab/bbknn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Batch balanced KNN

extra:
  recipe-maintainers:
    - jenzopr
