{% set name = "modlamp" %}
{% set version = "4.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "1b19d07192898ba9502b1c6a83d8324c39bb7fc83e02b174817a53fe43999486"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - lxml >=3.6.4
    - matplotlib-base >=1.5.1
    - nose >=1.3.7
    - numpy >=1.10.4
    - pandas >=0.18.1
    - pip
    - python
    - requests >=2.11.1
    - scikit-learn >=0.18.0
    - scipy >=0.17.0
    - setuptools >=20.2.2
  run:
    - lxml >=3.6.4
    - matplotlib-base >=1.5.1
    - nose >=1.3.7
    - numpy >=1.10.4
    - pandas >=0.18.1
    - python
    - requests >=2.11.1
    - scikit-learn >=0.18.0
    - scipy >=0.17.0
    - setuptools >=20.2.2

test:
  imports:
    - modlamp

about:
  home: "http://modlamp.org"
  license: "BSD"
  license_family: "BSD"
  summary: "python package for in silico peptide design and QSAR studies"
  doc_url: "https://modlamp.org/index.html"

extra:
  recipe-maintainers:
    - jaidevjoshi83
