{% set version = "2.2.0" %}

package:
  name: "python-sortedcontainers"
  version: {{ version }}
source:
  url: https://files.pythonhosted.org/packages/83/c9/466c0f9b42a0563366bb7c39906d9c6673315f81516f55e3a23a99f52234/sortedcontainers-2.2.0.tar.gz
  sha256: 331f5b7acb6bdfaf0b0646f5f86c087e414c9ae9d85e2076ad2eacb17ec2f4ff
build:
  number: 0
  noarch: python
requirements:
  host:
    - python
    - setuptools
  run:
    - python
test:
  imports:
    - sortedcontainers
about:
  home: https://pypi.org/project/sortedcontainers/#description
  dev_uri: http://www.grantjenks.com/docs/sortedcontainers/
  license: Apache 2.0
  summary: "sorted collections library, written in pure-Python, and fast as C-extensions"
