{% set version = "2.2.1" %}

package:
  name: "python-sortedcontainers"
  version: {{ version }}
source:
  url: https://files.pythonhosted.org/packages/ac/37/f03a8bcc83c4967c71d2d6bd5c28130c918b6731df36423d3f72d3d1f771/sortedcontainers-2.2.1.tar.gz
  sha256: 5a5259b9b8a45b3e970e2817b2710423c118a08c06a18cad1f09f59f15514c8b
build:
  number: 0
  noarch: python
requirements:
  host:
    - python
    - setuptools
  run:
    - python
test:
  imports:
    - sortedcontainers
about:
  home: https://pypi.org/project/sortedcontainers/#description
  dev_uri: http://www.grantjenks.com/docs/sortedcontainers/
  license: Apache 2.0
  summary: "sorted collections library, written in pure-Python, and fast as C-extensions"
