{% set version = "0.9.33" %}
{% set sha256 = "925a97afc854c069ecd106d6026782e079461b2b89fb598fdc7525f5a638616d" %}

package:
  name: diamond
  version: {{ version }}

source:
  url: https://github.com/bbuchfink/diamond/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost-cpp
    - zlib
  run:
    - boost-cpp
    - zlib

test:
  commands:
    - diamond --help 2>&1 > /dev/null

about:
  home: https://github.com/bbuchfink/diamond
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE
  summary: Accelerated BLAST compatible local sequence aligner

extra:
  identifiers:
    - biotools:Diamond
    - doi:10.1038/nmeth.3176
