{% set version = '2.8.6' %}

package:
  name: r-poppr
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/grunwaldlab/poppr/archive/v.{{ version }}.tar.gz
  sha256: ca641c3c52dd64773a9334ace43b20558ca8e0a75f77bf1045873e0cf282ad74

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - llvm-openmp # [osx]
  host:
    - r-base
    - r-boot
    - r-adegenet
    - r-ade4
    - r-ape
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-igraph
    - r-knitr
    - r-magrittr
    - r-pegas
    - r-phangorn
    - r-polysat
    - r-rlang
    - r-rmarkdown
    - r-shiny
    - r-testthat
    - r-vegan

  run:
    - r-base
    - r-boot
    - r-adegenet
    - r-ade4
    - r-ape
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-igraph
    - r-knitr
    - r-magrittr
    - r-pegas
    - r-phangorn
    - r-polysat
    - r-rlang
    - r-rmarkdown
    - r-shiny
    - r-testthat
    - r-vegan

test:
  commands:
    - $R -e "library('poppr')"

about:
  home: https://github.com/grunwaldlab/poppr
  license: GPL (>= 2)
  summary: An R package for genetic analysis of populations with mixed (clonal/sexual) reproduction
